[parameters]
# In case you specify a range, the experiment_name is the base for the name, the experiment folder will contain the parameter that varied and its value
experiment_name = "test"
width = 100
height = 100
n_tribes = 3
n_agents = 100
vision_radius = 4
step_count = 100
alpha = 0.2
trade_percentage = 0.3

# specify variables that have to be converted back into a function, not just a value
[functions]
spice_generator = "gen_spice_map"
river_generator = "gen_river"
location_generator = "random_locations"

# Specify the variables you would like to change, the list should read [start, end, step], like np.arange 
[ranges]
n_heaps = [3, 10, 1]
n_tribes = [2, 5, 1]
