# Number of trails for each configution
trails = 3

[parameters]
# In case you specify a range, the experiment_name is the base for the name, the experiment folder will contain the parameter that varied and its value
# !!! If you have your range set over multiple parameters, make sure all of them are also specified here, as this will the the base value for when iterating over the other variables
experiment_name = "test"
width = 100
height = 100
n_tribes = 2
n_agents = 100
vision_radius = 4
step_count = 100
alpha = 0.2
trade_percentage = 0.3

    [parameters.spice_kwargs]
    cov_range = [3, 9]
    total_spice = 1000

    # [parameters.river_kwargs]
    # cov_range = [3, 9]
    # total_spice = 1000
    #
    # [parameters.location_kwargs]
    # cov_range = [3, 9]
    # total_spice = 1000

# specify variables that have to be converted back into a function, not just a value
[functions]
spice_generator = "gen_spice_map"
river_generator = "gen_river_random"
location_generator = "split_tribes_locations"

# Specify the variables you would like to change, the list should read [start, end, step], like np.arange 
[ranges]
n_heaps = [3, 10, 5]
