trials = 10

[parameters]
experiment_name = "ofat_500_just_heaps2"
width = 50
height = 50
n_tribes = 2
n_agents = 390
n_heaps = 1
vision_radius = 10
step_count = 500
alpha = 0.5
trade_percentage = 0.5
spice_movement_bias = 1.0
tribe_movement_bias = 0.0
spice_threshold = 1290
spice_grow_threshold = 20


    [parameters.spice_kwargs]
    total_spice = 1300
    cov_range = [8, 20]

    [parameters.river_kwargs]
    cov_range = [10, 100]

    [parameters.location_kwargs]
    cov_range = [3, 9]

[functions]
spice_generator = "gen_spice_map"
river_generator = "no_river" 
location_generator = "random_locations"

[ranges]
n_tribes = [2, 3, 1]
n_agents = [199, 200, 1]
n_heaps = [1, 11, 1]
vision_radius = [9, 10, 1]
trade_percentage = [0.5, 0.6, 0.1]
spice_movement_bias = [0.9, 1.0, 0.1]
tribe_movement_bias = [0.0, 0.1, 0.1]
spice_threshold = [0, 2000, 200]