trials = 10

[parameters]
experiment_name = "ofat_results_sophie_coop_issue"
width = 100
height = 100
n_tribes = 2
n_agents = 900
n_heaps = 2
vision_radius = 10
step_count = 100
alpha = 0.5
trade_percentage = 0.5
spice_movement_bias = 1.0
tribe_movement_bias = 0.0
spice_threshold = 9000


    [parameters.spice_kwargs]
    total_spice = 10000
    cov_range = [8, 20]

    [parameters.river_kwargs]
    cov_range = [10, 100]
    total_spice = 1000

    [parameters.location_kwargs]
    cov_range = [3, 9]
    total_spice = 1000

[functions]
spice_generator = "gen_spice_map"
river_generator = "no_river" 
location_generator = "random_locations"

[ranges]
n_tribes = [2, 5, 1]
n_agents = [500, 1000, 10]
n_heaps = [1, 10, 1]
vision_radius = [10, 50, 2]
trade_percentage = [0.0, 1.0, 0.01]
spice_movement_bias = [0.0, 1.0, 0.01]
tribe_movement_bias = [0.0, 1.0, 0.01]
spice_threshold = [8000, 10000, 50]