trials = 30

[parameters]
experiment_name = "ofat_results_joana_finer_grain"
width = 500
height = 500
n_tribes = 2
n_agents = 100
n_heaps = 8
vision_radius = 5
step_count = 200
alpha = 0.4
trade_percentage = 0.5
spice_movement_bias = 1.0
tribe_movement_bias = 0.0
spice_threshold = 900


    [parameters.spice_kwargs]
    total_spice = 8000
    cov_range = [8, 20]

    [parameters.river_kwargs]
    cov_range = [10, 100]
    total_spice = 1000

    [parameters.location_kwargs]
    cov_range = [3, 9]
    total_spice = 1000

[functions]
spice_generator = "gen_spice_map"
river_generator = "gen_river_random" 
location_generator = "random_locations"

[ranges]
n_tribes = [2, 10, 1]
n_agents = [10, 200, 10]
n_heaps = [1, 50, 5]
vision_radius = [2, 20, 2]
alpha = [0.0, 1.0, 0.1]
trade_percentage = [0.0, 1.0, 0.1]
spice_movement_bias = [0.0, 1.0, 0.1]
tribe_movement_bias = [0.0, 1.0, 0.1]
spice_threshold = [1000, 8000, 1000]