trails = 3 

[parameters]
experiment_name = "ofat_analysis"
width = 100
height = 100
n_tribes = 3
n_agents = 100
n_heaps = 4
vision_radius = 4
step_count = 200
alpha = 0.2
trade_percentage = 0.3

[functions]
spice_generator = "gen_spice_map"
river_generator = "gen_river"
location_generator = "random_locations"

[integer_ranges]
n_tribes = [2, 10]
n_agents = [100, 1000]
n_heaps = [2, 10]
vision_radius = [3, 7]

[float_ranges]
alpha = [0.0, 0.8]
trade_percentage = [0.0, 0.8]
