trials = 30

[parameters]
experiment_name = "ofat_results"
experiment_name = "ofat_results_joana_finer_grain"
width = 100
height = 100
n_tribes = 2
n_agents = 200
n_tribes = 2
n_agents = 800
n_heaps = 8
vision_radius = 5
step_count = 200
vision_radius = 4
step_count = 200
alpha = 0.5
trade_percentage = 0.5
spice_movement_bias = 1.0
tribe_movement_bias = 0.0
spice_threshold = 900

spice_movement_bias = 1.0
tribe_movement_bias = 0.0
spice_threshold = 900


    [parameters.spice_kwargs]
    total_spice = 8000
    cov_range = [8, 20]
    total_spice = 8000
    cov_range = [8, 20]

    [parameters.river_kwargs]
    cov_range = [10, 100]
    total_spice = 1000

    [parameters.location_kwargs]
    cov_range = [3, 9]
    total_spice = 1000

[functions]
spice_generator = "gen_spice_map"
river_generator = "no_river" 
river_generator = "no_river" 
location_generator = "random_locations"

[ranges]
n_tribes = [2, 12, 1]
n_agents = [200, 1200, 100]
n_heaps = [2, 12, 1]
vision_radius = [2, 12, 1]
alpha = [0.0, 1.0, 0.1]
trade_percentage = [0.0, 1.0, 0.1]
spice_movement_bias = [0.0, 1.0, 0.1]
tribe_movement_bias = [0.0, 1.0, 0.1]
spice_threshold = [0, 1000, 100]