trials = 10

[parameters]
experiment_name = "ofat_results"
width = 100
height = 100
n_tribes = 2
n_agents = 200
n_heaps = 8
vision_radius = 5
step_count = 200
alpha = 0.5
trade_percentage = 0.5
spice_movement_bias = 1.0
tribe_movement_bias = 0.0
spice_threshold = 900


    [parameters.spice_kwargs]
    total_spice = 8000
    cov_range = [8, 20]

    [parameters.river_kwargs]
    empty = 0

    [parameters.location_kwargs]
    empty = 0

[functions]
spice_generator = "gen_spice_map"
river_generator = "no_river" 
location_generator = "random_locations"

[ranges]
n_tribes = [2, 12, 2]
n_heaps = [2, 12, 2]
vision_radius = [2, 12, 1]
alpha = [0.0, 1.0, 0.2]
trade_percentage = [0.0, 1.0, 0.2]
spice_movement_bias = [0.0, 1.0, 0.2]
tribe_movement_bias = [0.0, 1.0, 0.2]
spice_threshold = [0, 1000, 200]
