[parameters]
# In case you specify a range, the experiment_name is the base for the name, the experiment folder will contain the parameter that varied and its value
experiment_name = "test"
width = 100
height = 100
n_tribes = 3
n_agents = 100
n_heaps = 4
vision_radius = 4
step_count = 200
alpha = 0.2
trade_percentage = 0.3

[functions]
spice_generator = "gen_spice_map"
river_generator = "gen_river"
location_generator = "random_locations"


